// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7AjYocASnUxdv4nVcJ3LAWjVva4hjtGY',
    appId: '1:1049642488385:web:01278a9f8611cddc7b6cc0',
    messagingSenderId: '1049642488385',
    projectId: 'utm-shopping-app-5b973',
    authDomain: 'utm-shopping-app-5b973.firebaseapp.com',
    storageBucket: 'utm-shopping-app-5b973.appspot.com',
    measurementId: 'G-7E06NK4EV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnT0y3wrqnRtLEln__CoZb4lk-3JWZNz8',
    appId: '1:1049642488385:android:eab6445f1f78f7827b6cc0',
    messagingSenderId: '1049642488385',
    projectId: 'utm-shopping-app-5b973',
    storageBucket: 'utm-shopping-app-5b973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3dhrmOdREUeyr7Tn4brkeuzOAIdXFTg',
    appId: '1:1049642488385:ios:2ba3908ff6e5a97c7b6cc0',
    messagingSenderId: '1049642488385',
    projectId: 'utm-shopping-app-5b973',
    storageBucket: 'utm-shopping-app-5b973.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM3dhrmOdREUeyr7Tn4brkeuzOAIdXFTg',
    appId: '1:1049642488385:ios:e727af8da93860907b6cc0',
    messagingSenderId: '1049642488385',
    projectId: 'utm-shopping-app-5b973',
    storageBucket: 'utm-shopping-app-5b973.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
